site_name: OpenAgua docs
docs_dir: 'docs'
theme: 'mkdocs'
theme_dir: 'theme_extra'
pages:
    - About: index.md
    - User Guide:
        - 'Getting Started': 'user-guide/getting-started.md'
        - 'Water allocation logic': 'user-guide/allocation-logic.md'
        - 'Setting up a model': 'user-guide/setting-up-model.md'
        - 'Creating a network': 'user-guide/creating-network.md'
        - 'Creating scenarios': 'user-guide/creating-scenarios.md'
        - 'Entering data': 'user-guide/entering-data.md'
        - 'Running models': 'user-guide/running-models.md'
        - 'Viewing results': 'user-guide/viewing-results.md'
        - 'Exporting data': 'user-guide/exporting-data.md'
        - 'Sharing & collaboration': 'user-guide/collaboration.md'
        - 'Advanced data tools': 'user-guide/advanced-tools.md'
        - 'Glossary': 'user-guide/glossary.md'
    - Tutorials:
        - 'Tutorial 1': 'tutorials/tutorial1.md'
        - 'Tutorial 2': 'tutorials/tutorial2.md'
    - FAQs: faqs.md
    - The Team: the-team.md
    - Publications: publications.md

extra_css:
    - css/extra.css

markdown_extensions:
    - toc:
        permalink: True
